version: '3.8'
services:
  app_azure:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-vpn
    container_name: app_azure
    ports:
      - "3000:3000"
    volumes:
      - ./server.key:/app/certs/server.key:ro
      - ./server.crt:/app/certs/server.crt:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SSL_KEY_PATH=/app/certs/server.key
      - SSL_CERT_PATH=/app/certs/server.crt
      - DB_HOST=radius-mysql
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - app-network
    user: root
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
        compress: "true"
