services:
  app_azure:
    build:
      context: .
      dockerfile: Dockerfile
    image: gui_radius
    container_name: gui_radius
    ports:
      - "3001:3001"
    volumes:
      - ./server.key:/app/certs/server.key:ro
      - ./server.crt:/app/certs/server.crt:ro
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SSL_KEY_PATH=/app/certs/server.key
      - SSL_CERT_PATH=/app/certs/server.crt

    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - radius_gui_network
    user: root
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
        compress: "true"
networks:
  radius_gui_network:
    external: true
